name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.jpg
    - assets/phone1.jpg
    - assets/phone2.jpg
    - assets/phone3.jpg
    - assets/phone4.jpg
    - assets/phone5.jpg
    - assets/phone6.jpg